[build]
  # Directory to change to before starting a build
  base = ""
  
  # Directory to publish
  publish = "dist"
  
  # Build command
  command = "npm run build"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "20"

[[redirects]]
  # Single Page Application redirect for React Router
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"